# Makefile pour les utilitaire bimg
# actuellement chart et coupe
#
#    ######   ##  ##    ##   ######
#    ##   ##  ##  ###  ###  ##    ##
#    ######   ##  ########  ##
#    ##   ##  ##  ## ## ##  ##  #####
#    ##   ##  ##  ##    ##  ##    ##
#    ######   ##  ##    ##   ######
#
NCDF= -I/opt/software/SGI/netcdf/4.0/include -L/opt/software/SGI/netcdf/4.0/lib -lnetcdff -lnetcdf

# flag static is used to allow the use of CDFTOOLS in parallel with mpi_metamon
FFLAGS= -extend_source -static -O  $(NCDF) -assume byterecl -convert big_endian

#FFLAGS=  -assume byterecl  -convert big_endian -extend_source -O -I/home/molines/ncarg/include -I/usr/local/include \
         -I/data/molines/netcdf-3.6.2/include -L/data/molines/netcdf-3.6.2/lib
FFLAGS2= $(FFLAGS)
FC = ifort


CHARTOBJ = \
chart.o  color.o readpal.o readbimg.o util.o calcul.o\
deflim.o readargs.o tracecol.o isocontours.o val_table.o \
drawpalette.o checkfiles.o vectors.o lnblnk.o flush.o overlay.o sigma.o \
cdf.o

CHARTSRC = \
chart.f  color.f readpal.f readbimg.f util.f calcul.f\
deflim.f readargs.f tracecol.f isocontours.f val_table.f\
drawpalette.f checkfiles.F vectors.f lnblnk.f flush.f overlay.f sigma.f \
cdf.f

COUPEOBJ = \
coupe.o  color.o readpal.o readbimg.o util.o calcul.o\
deflim.o readargs.o tracecol.o isocontours.o val_table.o\
drawpalette.o checkfiles.o lnblnk.o flush.o overlay.o sigma.o \
cdf.o

COUPESRC = \
coupe.f  color.f readpal.f readbimg.f util.f calcul.f\
deflim.f readargs.f tracecol.f isocontours.f val_table.f\
drawpalette.f checkfiles.F lnblnk.f flush.f overlay.f sigma.f \
cdf.f


DEPEND = parameter.h common.h

BINDIR = $(HOME)/bin

all: chart coupe vecrot_opa

chart715: clean chparam chart coupe clean restoreparam 

chparam:
	/bin/cp parameter.715 parameter.h

restoreparam:
	/bin/cp parameter.755 parameter.h

chart: ${CHARTOBJ}
	ncargf90    $(FFLAGS)  ${CHARTOBJ} -o $@  -lnetcdff -lnetcdf

coupe: ${COUPEOBJ}
	ncargf90    $(FFLAGS) ${COUPEOBJ} -o $@  -lnetcdff -lnetcdf

clean:
	-/bin/rm -f *.o core *% *.trace *~

install:	chart	coupe	vecrot_opa
	mv -f chart $(BINDIR)/chart
	mv -f coupe $(BINDIR)/coupe
	mv -f vecrot_opa  $(BINDIR)/vecrot_opa

chart.total:
	cat $(CHARTSRC) > chart.total

coupe.total:
	cat $(COUPESRC) > coupe.total


common.h : parameter.h chart_version.h

vecrot_opa: vecrot_opa.f
	$(FC) $(FFLAGS2) -free vecrot_opa.f -o vecrot_opa  -lnetcdf -lnetcdff




# DO NOT DELETE
